communicationsManager -> nhsNotify "Communicates with the participant using"
communicationsManager -> pathwayCoordinator "Sends back invitation status payload"
communicationsManager -> businessAudit.inboundQueue "Writes appointment invitation statuses"
communicationsManager.API -> communicationsManager.eventHandler "Send communication event"
communicationsManager.eventHandler -> communicationsManager.businessLogic "Get Business Logic"
communicationsManager.eventHandler -> communicationsManager.extPayloadProcessor "Send events to process"
communicationsManager.extPayloadProcessor -> communicationsManager.db "Store payload"
communicationsManager.notifyAPI -> communicationsManager.db "Get the payload "
communicationsManager.notifyAPI -> nhsNotify "Send Payload"