communicationsManager -> nhsNotify "Communicates with the participant using"
communicationsManager -> pathwayCoordinator "Sends back invitation status payload"
communicationsManager -> businessAudit.businessAudit_queue "Writes appointment invitation statuses"
communicationsManager.communicationsManager_eventAPI -> communicationsManager.communicationManager_EventHandler "Send communication event"
communicationsManager.communicationManager_EventHandler -> communicationsManager.communicationManager_BusinessLogic "Get Business Logic"
communicationsManager.communicationManager_EventHandler -> communicationsManager.communicationManager_Extpayloadprocessor "Send events to process"
communicationsManager.communicationManager_Extpayloadprocessor -> communicationsManager.communicationManager_DBStore "Store payload"
communicationsManager.communicationManager_NotifyAPI -> communicationsManager.communicationManager_DBStore "Get the payload "
communicationsManager.communicationManager_NotifyAPI -> nhsNotify "Send Payload"