name: Deploy

on:
  push:
    branches:
      - current-architecture
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Install dependencies
        working-directory: eventcatalog/nhse-screening-catalog
        run: npm install
      - name: Build
        working-directory: eventcatalog/nhse-screening-catalog
        run: npm run build
# ---- Build Structurizr site using Docker ----
      - name: Prepare for c4 build
        run: |
          mkdir -p structurizr/build/site/

      - name: Build Structurizr site
        continue-on-error: true
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/structurizr:/var/model:rw \
            ghcr.io/avisi-cloud/structurizr-site-generatr \
            generate-site --workspace-file workspace.dsl \
      
      - name: Install tree
        run: sudo apt-get update && sudo apt-get install -y tree
          
      - name: Show folder structure
        run: tree -a -L 3

# ---- Prepare dist folder ----
      - name: Prepare dist folder for deploy
        run: |
          mkdir -p dist/eventcatalog
          mkdir -p dist/structurizr
          cp -r index.html dist/index.html
          cp -r eventcatalog/nhse-screening-catalog/dist/* dist/eventcatalog/
          cp -r structurizr/build/* dist/structurizr/

# ---- Deploy ----
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true
