name: Generate Structurizr PNGs

on:
  pull_request:

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      # Step 2: Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Download Structurizr Puppeteer repository
      - name: Download Structurizr Puppeteer
        run: |
          git clone https://github.com/structurizr/puppeteer.git
          cd puppeteer
          npm i puppeteer

      # Step 4: Start Structurizr Lite in Docker
      - name: Start Structurizr container
        run: |
          docker run --name structurizr-github-action \
          -d --rm -p 8080:8080 -v \
          ./:/usr/local/structurizr structurizr/lite

      # Step 5: Sleep until the docker container is ready
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash

      # Step 6: Test Structurizr Lite is accessible
      - name: Test Structurizr Lite accessibility
        run: |
          curl -I http://localhost:8080/workspace/diagrams

      # Step 7: Verify workspace.dsl exists in container
      - name: Check workspace.dsl in Structurizr container
        run: |
          docker exec structurizr-github-action ls /usr/local/structurizr
      
      # - name: Turn off apparmor
      #   run : |
      #       echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
      
      - name: Create AppArmor Profile
        run : |
          export CHROMIUM_BUILD_PATH=/@{HOME}/chromium/src/out/**/chrome
          cat | sudo tee /etc/apparmor.d/chrome-dev-builds <<EOF
          abi <abi/4.0>,
          include <tunables/global>

          profile chrome $CHROMIUM_BUILD_PATH flags=(unconfined) {
          userns,
          include if exists <local/chrome>
          }
          EOF
          sudo service apparmor reload  
      # Step 3: Restart AppArmor
      # - name: Restart AppArmor
      #   run: |
      #     sudo systemctl restart apparmor
      #     sudo apparmor_status

      # Step 8: Run Puppeteer script
      - name: Export diagrams
        run: |
          cd puppeteer
          node export-diagrams.js http://localhost:8080/workspace/diagrams png

      # Step 9: Copy pngs to images folder
      - name: Copy diagrams to /images
        run: |
          mkdir -p images
          cp puppeteer/*.png images/
          rm -rf puppeteer
      
      # Step 10: Commit and push diagrams to the PR branch
      - uses: stefanzweifel/git-auto-commit-action@v5
      
      # Step 11: Stop and remove the Docker container
      - name: Clean up Docker container
        if: always()
        run: |
          docker stop structurizr-github-action || true
          docker rm structurizr-github-action || true
