name: Generate Structurizr PNGs

on:
  pull_request:

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Download Structurizr Puppeteer repository
      - name: Download Structurizr Puppeteer
        run: |
          git clone https://github.com/structurizr/puppeteer.git
          cd puppeteer
          npm i puppeteer

      # Step 5: Start Structurizr Lite in Docker
      - name: Start Structurizr container
        run: |
          docker run --name structurizr-github-action \
          -it --rm -p 8080:8080 -v \
          ./:/usr/local/structurizr structurizr/lite

      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash

      # Step 6: Test Structurizr Lite is accessible
      - name: Test Structurizr Lite accessibility
        run: |
          curl -I http://localhost:8080

      # Step 7: Verify workspace.dsl exists in container
      - name: Check workspace.dsl in Structurizr container
        run: |
          docker exec structurizr-github-action ls /usr/local/structurizr
          
      # Step: Run Puppeteer script
      - name: Export diagrams
        run: |
          cd puppeteer
          node export-diagrams.js http://localhost:8080/workspace/diagrams png --output output

      # Step 6: Upload generated PNGs as artifacts
      - name: Upload diagrams as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: struct-diagrams
          path: output
          
      # Step 7: Stop and remove the Docker container
      - name: Clean up Docker container
        if: always()
        run: |
          docker stop structurizr-github-action || true
          docker rm structurizr-github-action || true
